services:
  maptoposter:
    build: .
    image: maptoposter-web:latest
    ports:
      - "8000:8000"
    # environment:
    #   - HTTP_PROXY=http://host.docker.internal:7897
    #   - HTTPS_PROXY=http://host.docker.internal:7897
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    volumes:
      - ./posters:/app/posters
      - ./cache:/app/cache
    restart: always
